fix: return an error if a non-HF model is used for fine-tuning (#436)
The fine-tuning job no longer supports a single GGUF file.

If we pass a single GGUF file, sft.py will hit the following error:

ValueError: Unrecognized model in ./base-model. Should have a
`model_type` key in its config.json, ...